create table if not exists ticket (
    id bigint generated by default as identity,
    body varchar(255),
    name varchar(255),
    subject varchar(255),
    primary key (id)
);
create table if not exists attachment (
    id uuid default random_uuid() not null,
    content blob,
    content_type varchar(255),
    filename varchar(255),
    ticket_id bigint,
    primary key (id),
    foreign key (ticket_id) references ticket
);

DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS users;
CREATE TABLE users (
    username VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL,
    PRIMARY KEY (username)
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_role_id INTEGER GENERATED ALWAYS AS IDENTITY,
    username VARCHAR(50) NOT NULL,
    role VARCHAR(50) NOT NULL,
    PRIMARY KEY (user_role_id),
    FOREIGN KEY (username) REFERENCES users(username)
);





CREATE TABLE IF NOT EXISTS book (
    bookId uuid default random_uuid() not null,
    name VARCHAR(50) NOT NULL,
    author VARCHAR(50) NOT NULL,
    price DOUBLE(50),
    description TEXT,
    coverPhoto BLOB,
    PRIMARY KEY (BookId)
    );

CREATE TABLE IF NOT EXISTS favouriteList (
    favouriteListId uuid default random_uuid() not null,
    PRIMARY key (favouriteListId),
    FOREIGN key (bookId) references book,
    FOREIGN key (username) references users
    );


CREATE TABLE IF NOT EXISTS cartItem (
    cartItemId uuid default random_uuid() not null,
    quantity INT,
    PRIMARY key (cartItemId),
    FOREIGN key (bookId) references book,
    FOREIGN key (username) references users
    );

